/*
DROP TABLE USER_TABLE;
DROP TABLE USERS_ROLE_TABLE;
DROP TABLE ALL_ROLE_TABLE;
DROP TABLE product_table;
DROP TABLE order_table;
DROP TABLE USER_ROLE;
*/

CREATE TABLE USER_TABLE(
    user_id VARCHAR2(150),
    email VARCHAR2(150),
    password VARCHAR2(150), 
    username VARCHAR2(150),  --USER
    first_name VARCHAR2(150), 
    last_name VARCHAR2(150),
    active INTEGER  --IS_ACTIVE_USER?
);

CREATE TABLE USERS_ROLE_TABLE(
    USER_ID VARCHAR2(150),
    ROLE_ID VARCHAR2(150)
);

CREATE TABLE ALL_ROLE_TABLE(
    role_id VARCHAR2(150) ,   --ID 1 OR 2
    role VARCHAR2(150)  -- ADMIN / USER
);

CREATE TABLE product_table (
    product_id VARCHAR2(150) PRIMARY KEY,
    product_name VARCHAR2(150),
    description VARCHAR2(150),
    quantity VARCHAR2(150),
    price VARCHAR2(150)
);

CREATE TABLE order_table(
    order_id VARCHAR2(150) PRIMARY KEY,  
    item_id VARCHAR2(150) ,
    user_id VARCHAR2(150)
);

COMMIT;

/* ROLE INSERTS */

INSERT INTO ALL_ROLE_TABLE (role_id, role)
VALUES (1, 'ROLE_ADMIN');
INSERT INTO ALL_ROLE_TABLE (role_id, role)
VALUES (2, 'ROLE_USER');

COMMIT;



CREATE SEQUENCE insertseq INCREMENT BY 1;

